# Generated by Django 3.2.5 on 2021-08-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(default='../static/img/None.jpg', upload_to='user_image/'),
        ),
    ]
