# Generated by Django 3.2.5 on 2021-08-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='media/user_image/%Y/%m/%d'),
        ),
    ]
