# Generated by Django 3.2.5 on 2021-07-30 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='survey_ess_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyessential'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='survey_opt_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyoptional'),
        ),
    ]
