# Generated by Django 3.2.5 on 2021-07-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kakao_id',
            field=models.CharField(default=0, max_length=200, unique=True, verbose_name='카카오 아이디'),
        ),
    ]
