# Generated by Django 3.2.6 on 2021-08-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_nickname',
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name='닉네임'),
        ),
    ]
