# Generated by Django 3.2.6 on 2021-08-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kakao_id',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='카카오 아이디'),
        ),
    ]
