# Generated by Django 3.2.6 on 2021-08-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_kakao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kakao_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='카카오 아이디'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_nickname',
            field=models.CharField(max_length=8, unique=True, verbose_name='닉네임'),
        ),
    ]
