# Generated by Django 3.2.6 on 2021-08-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
