# Generated by Django 3.2.5 on 2021-08-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkmate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domitory_post',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offcampus_post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
