# Generated by Django 3.2.5 on 2021-08-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkmate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domitory_post',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/domitory_image/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='offcampus_post',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/offcampus_image/%Y/%m/%d'),
        ),
    ]
