# Generated by Django 3.2.5 on 2021-08-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkmate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domitory_post',
            name='preface_2',
            field=models.CharField(choices=[('생활정보', '생활정보'), ('아람관', '아람관')], default='생활정보', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offcampus_post',
            name='preface_2',
            field=models.CharField(choices=[('생활정보', '생활정보'), ('원룸', '원룸')], default='생활정보', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domitory_post',
            name='preface',
            field=models.CharField(choices=[(1, '해결했어요'), (2, '질문있어요'), (3, '기숙사정보'), (4, '기숙사후기')], max_length=10),
        ),
        migrations.AlterField(
            model_name='offcampus_post',
            name='preface',
            field=models.CharField(choices=[(1, '해결했어요'), (2, '질문있어요'), (3, '원룸정보')], max_length=10),
        ),
    ]
