# Generated by Django 3.2.5 on 2021-08-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkmate', '0002_auto_20210804_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domitory_post',
            name='preface',
            field=models.CharField(choices=[('해결했어요', '해결했어요'), ('질문있어요', '질문있어요'), ('기숙사정보', '기숙사정보'), ('기숙사후기', '기숙사후기')], max_length=10),
        ),
        migrations.AlterField(
            model_name='offcampus_post',
            name='preface',
            field=models.CharField(choices=[('해결했어요', '해결했어요'), ('질문있어요', '질문있어요'), ('원룸정보', '원룸정보')], max_length=10),
        ),
    ]
