# Generated by Django 3.2.5 on 2021-08-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkmate', '0002_auto_20210806_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domitory_post',
            name='image',
            field=models.ImageField(blank=True, upload_to='domitory_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='offcampus_post',
            name='image',
            field=models.ImageField(blank=True, upload_to='offcampus_image/%Y/%m/%d'),
        ),
    ]
