# Generated by Django 3.2.6 on 2021-08-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyessential',
            name='dormitory_semester_end',
            field=models.CharField(choices=[('1', '1학기'), ('2', '여름방학'), ('3', '2학기'), ('4', '겨울방학')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='dormitory_semester_start',
            field=models.CharField(choices=[('1', '1학기'), ('2', '여름방학'), ('3', '2학기'), ('4', '겨울방학')], default='1', max_length=1),
        ),
    ]
