# Generated by Django 3.2.5 on 2021-07-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyessential',
            old_name='survey_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='surveyoptional',
            old_name='survey_id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='surveyessential',
            name='animal',
            field=models.CharField(blank=True, choices=[('0', '강아지'), ('1', '고양이')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='surveyessential',
            name='animal_other',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='surveyoptional',
            name='mbti',
            field=models.CharField(blank=True, choices=[('0', '자주'), ('1', '가끔'), ('2', '안함')], max_length=4, null=True),
        ),
    ]
