# Generated by Django 3.2.5 on 2021-07-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyessential',
            name='dormitory_number',
            field=models.CharField(choices=[('10', '10동'), ('8', '8동'), ('6', '6동'), ('3', '3동'), ('2', '2동'), ('1', '1동')], default='10', max_length=2),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='dormitory_semester_end',
            field=models.CharField(choices=[('1', '1학기'), ('S', '여름방학'), ('2', '2학기'), ('W', '겨울방학')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='dormitory_semester_start',
            field=models.CharField(choices=[('1', '1학기'), ('S', '여름방학'), ('2', '2학기'), ('W', '겨울방학')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='dormitory_year_end',
            field=models.CharField(choices=[('2021', '2021년도'), ('2022', '2022년도'), ('2023', '2023년도')], default='2021', max_length=4),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='dormitory_year_start',
            field=models.CharField(choices=[('2021', '2021년도'), ('2022', '2022년도'), ('2023', '2023년도')], default='2021', max_length=4),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='eat',
            field=models.CharField(choices=[('0', '코골이'), ('1', '이갈이')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='relationship',
            field=models.CharField(choices=[('0', '친하게'), ('1', '인사만')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='room_type',
            field=models.CharField(choices=[('0', '기숙사'), ('1', '자취')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='sleeping_habits',
            field=models.CharField(choices=[('0', '코골이'), ('1', '이갈이')], default='0', max_length=1),
        ),
    ]
