# Generated by Django 3.2.5 on 2021-08-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyessential',
            name='sleeping_habits_other',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
