# Generated by Django 3.2.5 on 2021-07-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210725_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyoptional',
            name='feel',
        ),
        migrations.AddField(
            model_name='surveyoptional',
            name='feel_cold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyoptional',
            name='feel_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyoptional',
            name='keyboard_noise',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='eat',
            field=models.CharField(choices=[('0', '식사도 방안에서'), ('1', '냄새 안 나는 음식만(간식)'), ('2', '나가서 먹음')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='surveyoptional',
            name='game',
            field=models.CharField(choices=[('0', '자주'), ('1', '가끔'), ('2', '안함')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='surveyoptional',
            name='keyboard',
            field=models.CharField(choices=[('0', '타이핑&게임 자주함'), ('1', '거의 안함')], default='0', max_length=1),
        ),
    ]
