# Generated by Django 3.2.5 on 2021-08-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210802_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyessential',
            name='animal_no',
            field=models.NullBooleanField(default=False),
        ),
    ]
