# Generated by Django 3.2.5 on 2021-07-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210725_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyessential',
            name='bed_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='grade',
            field=models.CharField(choices=[('1', '1학년'), ('2', '2학년'), ('3', '3학년'), ('4', '4학년'), ('5', '5학년'), ('6', '6학년')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='wakeup_time',
            field=models.TimeField(),
        ),
    ]
