# Generated by Django 3.2.5 on 2021-07-26 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210726_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyessential',
            name='earphone',
        ),
        migrations.RemoveField(
            model_name='surveyessential',
            name='sleeping_habits',
        ),
        migrations.AddField(
            model_name='surveyessential',
            name='call',
            field=models.CharField(choices=[('0', '예'), ('1', '아니요'), ('2', '짧은 통화만')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='surveyessential',
            name='earphones',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='surveyessential',
            name='sleeping_habits_nothing',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='surveyessential',
            name='sleeping_habits_snoring',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='surveyessential',
            name='sleeping_habits_teeth',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='bed_time',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='cleaning',
            field=models.IntegerField(default='3'),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='invite_friends',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='smoke',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='wakeup_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='surveyoptional',
            name='bug',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='surveyoptional',
            name='feel_cold',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='surveyoptional',
            name='feel_hot',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='surveyoptional',
            name='game',
            field=models.CharField(blank=True, choices=[('0', '자주'), ('1', '가끔'), ('2', '안함')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='surveyoptional',
            name='keyboard',
            field=models.CharField(blank=True, choices=[('0', '타이핑&게임 자주함'), ('1', '거의 안함')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='surveyoptional',
            name='keyboard_noise',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='surveyoptional',
            name='share',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='surveyoptional',
            name='toilet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyoptional',
            name='ventilate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
