# Generated by Django 3.2.5 on 2021-07-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20210726_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyessential',
            name='sleeping_habits_nothing',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='sleeping_habits_snoring',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='sleeping_habits_teeth',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyessential',
            name='smoke',
            field=models.BooleanField(default=False),
        ),
    ]
