# Generated by Django 3.2.5 on 2021-07-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20210726_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyessential',
            name='dormitory_number',
        ),
        migrations.AddField(
            model_name='surveyessential',
            name='dormitory_number_man',
            field=models.CharField(blank=True, choices=[('10', '10동'), ('8', '8동'), ('6', '6동'), ('3', '3동'), ('2', '2동'), ('1', '1동')], default='10', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='surveyessential',
            name='dormitory_number_woman',
            field=models.CharField(blank=True, choices=[('11', '11동'), ('9', '9동'), ('7', '7동'), ('5', '5동'), ('4', '4동')], default='11', max_length=2, null=True),
        ),
    ]
